# Generated by Django 3.2.3 on 2021-05-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firstyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regd_number', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=30)),
            ],
        ),
    ]
