# Generated by Django 3.2.3 on 2021-05-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstyear',
            name='branch',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
