# Generated by Django 3.2.3 on 2021-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_firstyear_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstyear',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
