# Generated by Django 3.2.3 on 2021-05-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_alter_firstyear_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='count_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reports', models.IntegerField()),
                ('daily_reports', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fourthyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regd_number', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=50)),
                ('branch', models.CharField(default='null', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='secondyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regd_number', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=50)),
                ('branch', models.CharField(default='null', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='thirdyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regd_number', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=50)),
                ('branch', models.CharField(default='null', max_length=10)),
            ],
        ),
    ]
