# Generated by Django 3.2.3 on 2021-05-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_count_info_fourthyear_secondyear_thirdyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count_info',
            old_name='daily_reports',
            new_name='id_number',
        ),
    ]
