# Generated by Django 3.2.3 on 2021-05-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0006_auto_20210526_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstyear',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='firstyear',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='fourthyear',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='fourthyear',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='secondyear',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='secondyear',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='thirdyear',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='thirdyear',
            name='full_name',
        ),
    ]
